### ISSUE TITLE
你好！我试了下这个项目，发现注册功能没法用啊？

### ISSUE THREAD

**Issue by mebest100** [ZeroWdd/Xiaomi#1]
你好！我试了下这个项目（git下来自己部署在本地），发现注册功能没法用啊？
点击注册以后，从chrome 的debug控制台，只能看到：

{"code":"001","msg":"可注册","data":null}

好像只能检测用户名是否占用，但是没法完成注册。

请问一下，是不是注册功能并没有完整实现？　谢谢！

**Comment by ZeroWdd** [comment]
可以使用呀，我这显示{"code":"001","msg":"注册成功","data":null}，你可以看看我部署的http://47.95.254.97:8080/#/，能够正常访问，没有问题。

**Comment by mebest100** [comment]
哦哦，我知道原因了，是密码有拦截规则：要以字母开头的密码，否则会被前端拦截住。

还有一个问题：就是我自己本地不熟页面上的图片全部都出不来，报404，chrome 控制台提示路径：http://localhost:3000/public/imgs/phone/xxx.png，但是我在vue项目的public目录下并没有找到imgs目录，请问这个数什么原因，谢谢！

**Comment by ZeroWdd** [comment]
> 哦哦，我知道原因了，是密码有拦截规则：要以字母开头的密码，否则会被前端拦截住。
> 
> 还有一个问题：就是我自己本地部署的页面上的图片全部都出不来，报404错误，chrome 控制台提示路径：[http://localhost:3000/public/imgs/phone/xxx.png，但是我在vue项目的public目录下并没有找到imgs目录，请问这个是什么原因，谢谢！](http://localhost:3000/public/imgs/phone/xxx.png%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%9C%A8vue%E9%A1%B9%E7%9B%AE%E7%9A%84public%E7%9B%AE%E5%BD%95%E4%B8%8B%E5%B9%B6%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0imgs%E7%9B%AE%E5%BD%95%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

**Comment by ZeroWdd** [comment]
> 哦哦，我知道原因了，是密码有拦截规则：要以字母开头的密码，否则会被前端拦截住。
> 
> 还有一个问题：就是我自己本地部署的页面上的图片全部都出不来，报404错误，chrome控制台提示路径：[http：// localhost：3000 / public / imgs / phone / xxx.png，但是我在vue项目的public目录下并没有找到imgs目录，请问这个是什么原因，谢谢！](http://localhost:3000/public/imgs/phone/xxx.png%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%9C%A8vue%E9%A1%B9%E7%9B%AE%E7%9A%84public%E7%9B%AE%E5%BD%95%E4%B8%8B%E5%B9%B6%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0imgs%E7%9B%AE%E5%BD%95%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

这个我是通过url直接访问图片，并没有对图片进行存储，如果你想将图片存储就要自己实现了。
